"""create room bookings

Revision ID: 2f8110355a4d
Revises: 933961688f31
Create Date: 2026-08-09 15:21:17.468529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8110355a4d'
down_revision: Union[str, Sequence[str], None] = '933961688f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=32), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=320), nullable=True),
    sa.Column('guest_phone', sa.String(length=50), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('nightly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', name='room_booking_status', native_enum=False, create_constraint=True), server_default='confirmed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('adults > 0', name='ck_room_bookings_adults_positive'),
    sa.CheckConstraint('char_length(currency) = 3 AND currency = upper(currency)', name='ck_room_bookings_currency_code'),
    sa.CheckConstraint('check_out > check_in', name='ck_room_bookings_valid_stay'),
    sa.CheckConstraint('children >= 0', name='ck_room_bookings_children_non_negative'),
    sa.CheckConstraint('nightly_rate >= 0', name='ck_room_bookings_nightly_rate_non_negative'),
    sa.CheckConstraint('rooms > 0', name='ck_room_bookings_rooms_positive'),
    sa.CheckConstraint('total_amount >= 0', name='ck_room_bookings_total_amount_non_negative'),
    sa.ForeignKeyConstraint(['organization_id', 'property_id', 'room_type_id'], ['room_types.organization_id', 'room_types.property_id', 'room_types.id'], name='fk_room_bookings_room_type_tenant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_code', name='uq_room_bookings_confirmation_code')
    )
    op.create_index('ix_room_bookings_availability', 'room_bookings', ['organization_id', 'property_id', 'room_type_id', 'status', 'check_in', 'check_out'], unique=False)
    # ### end Alembic commands ###
    op.execute(
    """
    ALTER TABLE public.room_bookings
    ENABLE ROW LEVEL SECURITY
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_bookings_availability', table_name='room_bookings')
    op.drop_table('room_bookings')
    # ### end Alembic commands ###
