"""create property tools

Revision ID: 86f9c1691f20
Revises: b6f2d4a91c30
Create Date: 2026-08-09 00:39:26.135834

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "86f9c1691f20"
down_revision: str | Sequence[str] | None = "b6f2d4a91c30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "property_tools",
        sa.Column("id", sa.UUID(),server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "property_id"],
            ["properties.organization_id", "properties.id"],
            name="fk_property_tools_property_organization",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "property_id", "tool_name", name="uq_property_tools_property_id_tool_name"
        ),
    )
    # property_tools contains administrative capability configuration.
    #
    # All reads/writes currently go through FastAPI, so direct authenticated
    # Supabase access is intentionally blocked. Enabling RLS without adding
    # client policies gives us that protection.
    op.execute(
        """
        ALTER TABLE public.property_tools
        ENABLE ROW LEVEL SECURITY
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("property_tools")
    # ### end Alembic commands ###
