import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const SB='https://msxnhjlsxtqdgvzditzg.supabase.co',KEY='sb_publishable_BmnVrRXUUxmAENWPZVOL8A_QAHf1Okg',API='/api/v1',PC=(new URLSearchParams(location.search).get('property')||'DGHDEL').toUpperCase(),supabase=createClient(SB,KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],state={session:null,tenant:null,chat:null,bootstrap:null};
const roomImages=['https://images.unsplash.com/photo-1743410975074-4be327c0ae63?auto=format&fit=crop&fm=jpg&q=78&w=1200','https://images.unsplash.com/photo-1776361984994-089a9df800f6?auto=format&fit=crop&fm=jpg&q=78&w=1200','https://images.unsplash.com/photo-1762254923872-5bdc4210eb90?auto=format&fit=crop&fm=jpg&q=78&w=1200'];
function toast(x){$('#toast').textContent=x;$('#toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').style.display='none',2600)}
function money(v,c='INR'){try{return new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:0}).format(+v)}catch{return c+' '+v}}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function req(url,opt={}){let r=await fetch(url,opt),d=await r.json().catch(()=>null);if(!r.ok)throw Error(typeof d?.detail==='string'?d.detail:'Request failed '+r.status);return d}
function inlineMd(s){return esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*([^*]+)\*/g,'<em>$1</em>')}
function renderMarkdown(text=''){const lines=String(text).replace(/\r/g,'').split('\n');let out=[],i=0;while(i<lines.length){let line=lines[i].trimEnd();if(!line.trim()){i++;continue}if(/^\|.*\|$/.test(line)&&i+1<lines.length&&/^\|?\s*:?-{3,}/.test(lines[i+1])){let rows=[];while(i<lines.length&&/^\|.*\|$/.test(lines[i].trim())){rows.push(lines[i].trim());i++}if(rows.length>1){rows.splice(1,1);let parsed=rows.map(r=>r.replace(/^\||\|$/g,'').split('|').map(c=>c.trim()));out.push('<div class="md-table-wrap"><table class="md-table"><thead><tr>'+parsed[0].map(c=>'<th>'+inlineMd(c)+'</th>').join('')+'</tr></thead><tbody>'+parsed.slice(1).map(r=>'<tr>'+r.map(c=>'<td>'+inlineMd(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>');continue}}if(/^#{1,3}\s+/.test(line)){let level=Math.min(3,(line.match(/^#+/)||['#'])[0].length);out.push(`<h${level}>${inlineMd(line.replace(/^#{1,3}\s+/,''))}</h${level}>`);i++;continue}if(/^[-*]\s+/.test(line)){let items=[];while(i<lines.length&&/^[-*]\s+/.test(lines[i].trim())){items.push(lines[i].trim().replace(/^[-*]\s+/,''));i++}out.push('<ul>'+items.map(x=>'<li>'+inlineMd(x)+'</li>').join('')+'</ul>');continue}if(/^\d+\.\s+/.test(line)){let items=[];while(i<lines.length&&/^\d+\.\s+/.test(lines[i].trim())){items.push(lines[i].trim().replace(/^\d+\.\s+/,''));i++}out.push('<ol>'+items.map(x=>'<li>'+inlineMd(x)+'</li>').join('')+'</ol>');continue}let para=[line.trim()];i++;while(i<lines.length&&lines[i].trim()&&!/^[-*]\s+/.test(lines[i].trim())&&!/^\d+\.\s+/.test(lines[i].trim())&&!/^\|.*\|$/.test(lines[i].trim())&&!/^#{1,3}\s+/.test(lines[i].trim())){para.push(lines[i].trim());i++}out.push('<p>'+inlineMd(para.join(' '))+'</p>')}return out.join('')}
function stripMd(s=''){return String(s).replace(/\*\*/g,'').replace(/`/g,'').replace(/^[-*]\s+/gm,'• ').replace(/^#{1,3}\s+/gm,'').replace(/\|/g,' ')}
function appendMessage(role,text){let d=document.createElement('div');d.className='msg '+role;if(role==='assistant')d.innerHTML=renderMarkdown(text);else d.textContent=text;$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight;return d}
function bookingCard(text){let code=(text.match(/HMS-[A-Z0-9-]+/i)||[])[0];if(!code||!/reservation is confirmed/i.test(text))return;let c=document.createElement('div');c.className='booking-confirm';c.innerHTML=`<div class="check">✓</div><h4>Reservation confirmed</h4><div class="booking-code">${esc(code)}</div><div class="booking-details">Your booking is secured. Keep this confirmation for check-in.</div><button class="download-confirm">↓ Download confirmation</button>`;c.querySelector('button').onclick=()=>downloadConfirmation(text,code);$('#chat').appendChild(c);$('#chat').scrollTop=$('#chat').scrollHeight}
function downloadConfirmation(text,code){let clean=stripMd(text),html=`<!doctype html><meta charset="utf-8"><title>${esc(code)} · Aurelia House</title><style>body{font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17231e;max-width:720px;margin:60px auto;padding:0 24px}h1{font:42px Georgia,serif;margin-bottom:4px}.code{color:#8a6a3e;font-weight:700}.box{margin-top:28px;padding:24px;border:1px solid #ddd6ca;border-radius:16px;white-space:pre-wrap}.foot{margin-top:34px;color:#69736e;font-size:13px}</style><h1>Aurelia House</h1><div>New Delhi · Reservation confirmation</div><p class="code">${esc(code)}</p><div class="box">${esc(clean)}</div><div class="foot">Generated from your Aurelia Concierge reservation.</div>`;let blob=new Blob([html],{type:'text/html'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Aurelia-${code}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function chips(a){$('#chips').innerHTML='';a.forEach(x=>{let b=document.createElement('button');b.textContent=x;b.onclick=()=>chat(x);$('#chips').appendChild(b)})}
function clearBookingActions(){let c=$('#bookingActions');if(!c)return;c.innerHTML='';c.classList.add('hidden')}
function renderBookingActions(pendingBooking){let c=$('#bookingActions');if(!c||!pendingBooking){clearBookingActions();return}let total=money(pendingBooking.total_amount,pendingBooking.currency);c.innerHTML=`<div class="booking-action-card"><div class="booking-action-copy"><div class="booking-action-eyebrow">Ready to book</div><div class="booking-action-room">${esc(pendingBooking.room_type_name)}</div><div class="booking-action-price">${esc(total)} total</div></div><button id="confirmBookingAction" class="booking-action-confirm">Confirm booking · ${esc(total)}</button><div class="booking-action-secondary"><button id="askBookingQuestion" type="button">Ask a question</button><button id="bookLaterAction" type="button">Book later</button></div><div class="booking-action-note">No room is booked until you confirm.</div></div>`;c.classList.remove('hidden');$('#confirmBookingAction').onclick=()=>{clearBookingActions();chat('Confirm booking')};$('#askBookingQuestion').onclick=()=>$('#chatInput').focus();$('#bookLaterAction').onclick=()=>{clearBookingActions();chat('Maybe later',{suppressBookingActions:true})}}
async function boot(){try{let d=await req(`${API}/widget/${PC}/bootstrap`);state.bootstrap=d;$('#roomGrid').innerHTML=d.rooms.map((r,i)=>`<article class="room-card"><div class="room-image" style="background-image:url('${roomImages[i%roomImages.length]}')"></div><div class="room-body"><div class="room-top"><h3 class="room-title">${esc(r.name)}</h3><div class="room-price">${esc(money(r.nightly_rate,r.currency))}<small>per night</small></div></div><div class="room-meta">Up to ${r.max_adults} adults${r.max_children?' + '+r.max_children+' children':''} · ${esc(r.code)}</div><button class="room-cta" data-room="${esc(r.name)}">Check availability →</button></div></article>`).join('');$$('[data-room]').forEach(b=>b.onclick=()=>{openChat();chat(`Is ${b.dataset.room} available?`)})}catch(e){toast(e.message)}}
function openChat(){let p=$('#panel');p.classList.remove('hidden');if(!$('#chat').children.length){appendMessage('assistant','Welcome to **Aurelia House**. I can help with room availability, hotel details, and reservations.');chips(['What rooms are available?','What time is checkout?','Is parking available?'])}}
$('#launcher').onclick=openChat;$('#heroConcierge').onclick=openChat;$('#roomsConcierge').onclick=openChat;$('#storyConcierge').onclick=openChat;$('#footerConcierge').onclick=e=>{e.preventDefault();openChat()};$('#checkStay').onclick=()=>{openChat();chat('I would like to check room availability for a stay.')};$('#close').onclick=()=>$('#panel').classList.add('hidden');
async function chat(text,{suppressBookingActions=false}={}){appendMessage('user',text);chips([]);clearBookingActions();try{let body={message:text};if(state.chat)body.session_id=state.chat;let d=await req(`${API}/widget/${PC}/chat`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});state.chat=d.session_id;(d.tool_calls||[]).forEach(t=>{let p=document.createElement('div');p.className='tool';p.textContent=t.name;$('#chat').appendChild(p)});appendMessage('assistant',d.answer);bookingCard(d.answer);(d.sources||[]).forEach(s=>{let p=document.createElement('div');p.className='source';p.textContent='Source · '+s.document_title+(s.page_number?' · page '+s.page_number:'');$('#chat').appendChild(p)});if(d.next_action==='confirm_booking'&&d.pending_booking&&!suppressBookingActions){chips([]);renderBookingActions(d.pending_booking)}else{clearBookingActions();chips(['Ask another question','Check room availability'])}$('#chat').scrollTop=$('#chat').scrollHeight}catch(e){clearBookingActions();appendMessage('assistant','I’m sorry, I couldn’t complete that request. '+e.message)}}
$('#send').onclick=()=>{let v=$('#chatInput').value.trim();if(v){$('#chatInput').value='';chat(v)}};$('#chatInput').onkeydown=e=>{if(e.key==='Enter')$('#send').click()};
function showAdmin(){$('#guest').classList.add('hidden');$('#admin').classList.remove('hidden');admin()}function showGuest(){$('#admin').classList.add('hidden');$('#guest').classList.remove('hidden')}$('#mode').onclick=showAdmin;$('#guestMode').onclick=showGuest;
$$('.nav[data-sec]').forEach(b=>b.onclick=()=>{$$('.nav[data-sec]').forEach(x=>x.classList.toggle('active',x===b));$$('.adminsec').forEach(s=>s.classList.toggle('active',s.id==='sec-'+b.dataset.sec))});
async function admin(){let{data:{session}}=await supabase.auth.getSession();if(!session){$('#login').classList.remove('hidden');return}state.session=session;await loadAdmin()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();let{data,error}=await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error){$('#loginErr').textContent=error.message;return}state.session=data.session;$('#login').classList.add('hidden');await loadAdmin()};
async function headers(extra={}){return{authorization:'Bearer '+state.session.access_token,'X-Organization-ID':state.tenant.organization_id,'X-Property-ID':state.tenant.property_id,...extra}}
async function loadAdmin(){try{let os=await req(API+'/onboarding/status',{headers:{authorization:'Bearer '+state.session.access_token}});state.tenant={organization_id:os.organization_id,property_id:os.property_id};let d=await req(API+'/admin/dashboard',{headers:await headers()});$('#propName').textContent=d.property.property_name;$('#propOrg').textContent=d.property.organization_name;$('#adminSub').textContent=d.property.property_name;$('#s1').textContent=d.metrics.guest_sessions_today;$('#s2').textContent=d.metrics.bookings_this_week;$('#s3').textContent=d.metrics.questions_answered;$('#knowledgeList').innerHTML=d.knowledge_documents.map(x=>`<div class="row"><div class="grow"><b>${esc(x.title)}</b><div class="muted">${x.chunk_count} chunks · updated ${new Date(x.updated_at).toLocaleDateString()}</div></div><span class="status">${esc(x.status)}</span></div>`).join('')||'<div class="row muted">No documents yet</div>';$('#toolsList').innerHTML=d.tools.map(x=>`<div class="row"><div class="grow"><b>${esc(x.tool_name.replaceAll('_',' '))}</b></div><button class="switch ${x.enabled?'on':''}" data-tool="${esc(x.tool_name)}"></button></div>`).join('');$$('[data-tool]').forEach(b=>b.onclick=async()=>{let on=!b.classList.contains('on');try{await req(API+'/admin/property-tools/'+b.dataset.tool,{method:'PUT',headers:await headers({'content-type':'application/json'}),body:JSON.stringify({enabled:on,configuration:{}})});await loadAdmin()}catch(e){toast(e.message)}});$('#roomsBody').innerHTML=d.rooms.map(r=>`<tr><td>${esc(r.code)}</td><td><b>${esc(r.name)}</b></td><td>${r.max_adults}${r.max_children?' + '+r.max_children:''}</td><td>${esc(money(r.nightly_rate,r.currency))}</td><td>${r.total_rooms}</td><td><span class="status">${r.is_active?'Active':'Inactive'}</span></td></tr>`).join('');$('#resBody').innerHTML=d.bookings.map(b=>`<tr><td>${esc(b.confirmation_code)}</td><td><b>${esc(b.guest_name)}</b></td><td>${esc(b.room_type_name)}</td><td>${esc(b.check_in+' → '+b.check_out)}</td><td>${esc(money(b.total_amount,b.currency))}</td><td><span class="status">${esc(b.status)}</span></td></tr>`).join('')}catch(e){toast(e.message)}}
$('#upload').onclick=()=>{let i=document.createElement('input');i.type='file';i.accept='.pdf,application/pdf';i.onchange=async()=>{let f=i.files[0];if(!f)return;let fd=new FormData();fd.append('title',f.name.replace(/\.pdf$/i,''));fd.append('source_key',f.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+Date.now());fd.append('file',f);try{await req(API+'/admin/knowledge/documents/pdf',{method:'POST',headers:await headers(),body:fd});toast('Document uploaded');await loadAdmin()}catch(e){toast(e.message)}};i.click()};
function roomModal(open){$('#roomModal').classList.toggle('hidden',!open)}$('#addRoom').onclick=()=>roomModal(true);$('#closeRoomModal').onclick=()=>roomModal(false);$('#cancelRoom').onclick=()=>roomModal(false);$('#roomModal').onclick=e=>{if(e.target===$('#roomModal'))roomModal(false)};
$('#roomForm').onsubmit=async e=>{e.preventDefault();let payload={code:$('#roomCode').value.trim().toUpperCase(),name:$('#roomName').value.trim(),description:$('#roomDescription').value.trim()||null,total_rooms:+$('#roomTotal').value,max_adults:+$('#roomAdults').value,max_children:+$('#roomChildren').value,nightly_rate:+$('#roomRate').value,currency:$('#roomCurrency').value.trim().toUpperCase(),is_active:$('#roomActive').value==='true'};try{await req(API+'/admin/room-types',{method:'POST',headers:await headers({'content-type':'application/json'}),body:JSON.stringify(payload)});toast('Room type created');$('#roomForm').reset();$('#roomTotal').value=1;$('#roomAdults').value=2;$('#roomChildren').value=0;$('#roomCurrency').value='INR';roomModal(false);await Promise.all([loadAdmin(),boot()])}catch(err){toast(err.message)}};
boot();
