from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from typing import Any, cast

import openai
import structlog
from openai import AsyncOpenAI
from openai.types.chat import (
    ChatCompletionMessageFunctionToolCall,
)
from pydantic import BaseModel

from app.core.config import get_settings
from app.modules.assistant.tools.knowledge import (
    KNOWLEDGE_SEARCH_TOOL_NAME,
    KnowledgeSearchToolInput,
)
from app.modules.assistant.tools.rooms import (
    ROOM_AVAILABILITY_TOOL_NAME,
    RoomAvailabilityToolInput,
)
from app.modules.property_tools import (
    PropertyToolName,
)

logger = structlog.get_logger(__name__)


AssistantMessage = dict[str, Any]


class AssistantLlmError(Exception):
    """Base error raised by the assistant LLM boundary."""


class AssistantLlmConfigurationError(AssistantLlmError):
    """Raised when the LLM is not configured."""


class AssistantLlmRequestError(AssistantLlmError):
    """Raised when an LLM request fails."""


class AssistantLlmRateLimitError(AssistantLlmRequestError):
    """Raised when provider rate limit is reached."""


class AssistantLlmResponseError(AssistantLlmError):
    """Raised for unusable provider responses."""


@dataclass(
    frozen=True,
    slots=True,
)
class AssistantFunctionCall:
    """
    One function call requested by the model.

    arguments is raw JSON generated by the LLM.
    The service validates it before execution.
    """

    call_id: str
    name: str
    arguments: str


@dataclass(
    frozen=True,
    slots=True,
)
class AssistantModelTurn:
    """
    Provider-neutral representation of one LLM turn.
    """

    text: str | None

    tool_calls: list[AssistantFunctionCall]

    assistant_message: AssistantMessage

    request_id: str | None


def build_function_tool_definition(
    *,
    name: str,
    description: str,
    input_model: type[BaseModel],
) -> dict[str, Any]:
    """
    Build one OpenAI-compatible function tool.

    Pydantic is the single source of truth for
    accepted arguments.
    """

    return {
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": (input_model.model_json_schema()),
            "strict": False,
        },
    }


def build_knowledge_search_tool_definition() -> dict[str, Any]:
    """
    Build knowledge_search.

    Kept as a separate function because existing
    tests already use it.
    """

    return build_function_tool_definition(
        name=KNOWLEDGE_SEARCH_TOOL_NAME,
        description=(
            "Search this hotel's active knowledge "
            "documents for property-specific "
            "policies, facilities, services, "
            "dining, events, check-in, checkout, "
            "cancellations, pets, parking, and "
            "other guest information. Use only "
            "the relevant returned information "
            "when answering the guest."
        ),
        input_model=KnowledgeSearchToolInput,
    )


def build_room_availability_tool_definition() -> dict[str, Any]:
    """
    Build live room availability capability.
    """

    return build_function_tool_definition(
        name=ROOM_AVAILABILITY_TOOL_NAME,
        description=(
            "Check live room availability and "
            "current rates for specified dates. "
            "Use this for available-room questions, "
            "specific or partial room-type names, "
            "guest capacity, number of available "
            "rooms, and current room rates. "
            "Never use hotel knowledge documents "
            "as proof of live availability."
        ),
        input_model=RoomAvailabilityToolInput,
    )


def build_assistant_tool_definitions(
    enabled_tools: set[PropertyToolName],
) -> list[dict[str, Any]]:
    """
    Build only the tools enabled for this property.

    room_booking deliberately remains unexposed
    until confirmation/idempotency is implemented.
    """

    definitions: list[dict[str, Any]] = []

    if PropertyToolName.KNOWLEDGE_SEARCH in enabled_tools:
        definitions.append(build_knowledge_search_tool_definition())

    if PropertyToolName.ROOM_AVAILABILITY in enabled_tools:
        definitions.append(build_room_availability_tool_definition())

    return definitions


@lru_cache(maxsize=1)
def get_llm_client() -> AsyncOpenAI:
    """
    Create and cache the asynchronous
    OpenAI-compatible client.

    Groq configuration example:

    LLM_BASE_URL=https://api.groq.com/openai/v1
    LLM_API_KEY=gsk_...
    LLM_MODEL=llama-3.3-70b-versatile
    """

    settings = get_settings()

    if settings.llm_api_key is None:
        raise AssistantLlmConfigurationError("LLM_API_KEY is not configured.")

    if settings.llm_model is None or not settings.llm_model.strip():
        raise AssistantLlmConfigurationError("LLM_MODEL is not configured.")

    client_options: dict[str, Any] = {
        "api_key": (settings.llm_api_key.get_secret_value()),
        "timeout": (settings.llm_timeout_seconds),
    }

    if settings.llm_base_url is not None and settings.llm_base_url.strip():
        client_options["base_url"] = settings.llm_base_url.strip()

    return AsyncOpenAI(
        **client_options,
    )


def build_assistant_message(
    *,
    content: str | None,
    tool_calls: list[AssistantFunctionCall],
) -> AssistantMessage:
    """
    Rebuild the assistant tool-call message needed
    by the provider on the next turn.
    """

    assistant_message: AssistantMessage = {
        "role": "assistant",
    }

    if content is not None:
        assistant_message["content"] = content

    if tool_calls:
        assistant_message["tool_calls"] = [
            {
                "id": tool_call.call_id,
                "type": "function",
                "function": {
                    "name": (tool_call.name),
                    "arguments": (tool_call.arguments),
                },
            }
            for tool_call in tool_calls
        ]

    return assistant_message


async def generate_assistant_turn(
    messages: list[AssistantMessage],
    *,
    tool_definitions: list[dict[str, Any]],
) -> AssistantModelTurn:
    """
    Send one turn to Groq/OpenAI-compatible LLM.

    The service decides which tools are enabled.
    This module only handles communication with
    the provider.
    """

    settings = get_settings()

    if settings.llm_model is None or not settings.llm_model.strip():
        raise AssistantLlmConfigurationError("LLM_MODEL is not configured.")

    client = get_llm_client()

    try:
        request_options: dict[
            str,
            Any,
        ] = {
            "model": (settings.llm_model.strip()),
            "messages": cast(
                Any,
                messages,
            ),
            "max_completion_tokens": (settings.llm_max_output_tokens),
        }

        if tool_definitions:
            request_options["tools"] = cast(
                Any,
                tool_definitions,
            )

            request_options["tool_choice"] = "auto"

        completion = await client.chat.completions.create(**request_options)

    except openai.APITimeoutError as exc:
        raise AssistantLlmRequestError("The language-model request timed out.") from exc

    except openai.APIConnectionError as exc:
        raise AssistantLlmRequestError("The language-model provider could not be reached.") from exc

    except openai.RateLimitError as exc:
        raise AssistantLlmRateLimitError(
            "The Hotel Assistant is temporarily busy. Please retry shortly."
        ) from exc

    except openai.APIStatusError as exc:
        logger.exception(
            "assistant_llm_status_error",
            status_code=exc.status_code,
            request_id=getattr(
                exc,
                "request_id",
                None,
            ),
        )

        raise AssistantLlmRequestError("The language-model provider rejected the request.") from exc

    except openai.OpenAIError as exc:
        raise AssistantLlmRequestError("The language-model request failed.") from exc

    if not completion.choices:
        raise AssistantLlmResponseError("The language model returned no completion choices.")

    message = completion.choices[0].message

    text: str | None = None

    if message.content is not None:
        normalized_text = message.content.strip()

        if normalized_text:
            text = normalized_text

    normalized_tool_calls: list[AssistantFunctionCall] = []

    for tool_call in message.tool_calls or []:
        if not isinstance(
            tool_call,
            ChatCompletionMessageFunctionToolCall,
        ):
            raise AssistantLlmResponseError(
                "The language model returned an unsupported custom tool call."
            )

        normalized_tool_calls.append(
            AssistantFunctionCall(
                call_id=tool_call.id,
                name=(tool_call.function.name),
                arguments=(tool_call.function.arguments),
            )
        )

    assistant_message = build_assistant_message(
        content=message.content,
        tool_calls=(normalized_tool_calls),
    )

    request_id_value = getattr(
        completion,
        "_request_id",
        None,
    )

    request_id = (
        request_id_value
        if isinstance(
            request_id_value,
            str,
        )
        else None
    )

    return AssistantModelTurn(
        text=text,
        tool_calls=(normalized_tool_calls),
        assistant_message=(assistant_message),
        request_id=request_id,
    )
